{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_003.Test_Credence_003 object at 0x000002909AE6E110>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_003.py:14: AssertionError"}, "start": 1690662657894, "stop": 1690662657894, "uuid": "e13837d3-cd4e-4a21-a655-c1cd3b7eeeaf", "historyId": "a829eabb1d8f59b995ce77b8f82570d1", "testCaseId": "a829eabb1d8f59b995ce77b8f82570d1", "fullName": "test_003.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "LAPTOP-0UVS3GMM"}, {"name": "thread", "value": "19244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_003"}]}